include ./onedark.conf

# remote control
allow_remote_control yes

# font
font_size 14.0
font_family FiraCode Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto

# window
adjust_line_height 14
window_padding_width 10.0

# mouse
copy_on_select yes

# cursor
cursor_shape beam
cursor_blink_interval 0

